### ISSUE TITLE
Rest.request call timing out doesn't result in the errorMessage being set in the httpPaginatedResponse?

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-go#192]
not quite clear what happened, but see https://ably-real-time.slack.com/archives/CPEP9K69Y/p1598630469024500

**Comment by tcard** [comment]
I'll copy the relevant bits here for context:

> I'm not familiar with the go client, but plausibly the client request was timing out (by default we have a client request timeout of 10s) but was failing to return an appropriate timeout ErrorInfo to the requesting code?
To be clear you got an errorinfo object that had a statusCode, but no code or message?  (Or if not where was the statusCode coming from?)

(The answer is yes: a `HTTPPaginatedResponse` with `StatusCode >= 300` but no `ErrorMessage`.)

As things stand now (which is, unfortunately, quite divergent from the spec in lots of details), requests by default don't have a timeout unless the client code passes its own HTTP client in the ClientOptions. So it's probably not that, but an actual error response or broken connection from the server. (Unless you mean the server/some middleware sets its own timeout for client requests?)

As to how that results in an empty `ErrorMessage`, I'm looking into it.

**Comment by tcard** [comment]
So from what I can tell:

* If this was a timeout or broken connection, `err` wouldn't have been nil. The client got a valid HTTP response.
* `ErrorMessage` (similarly to`ErrorCode`) is just the response's `X-Ably-Errormessage` header, if there is one.

The spec doesn't really say what to do if the HTTP request is performed but the response isn't formatted like a PaginatedResult, ie. doesn't have a `X-Ably-Errormessage` but has an error HTTP status. I'd say a sensible thing to do is to return an error instead of a half-baked HTTPPaginatedResult as we're seeing here.

**Comment by tcard** [comment]
> I'd say a sensible thing to do is to return an error instead of a half-baked HTTPPaginatedResult as we're seeing here.

I've opened #194 to do that. Also, #193 adds the `httpRequestTimeout` option.
