### ISSUE TITLE
Document the project structure in our contributing guide

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-go#350]
We'll want to work on https://github.com/ably/ably-go/issues/340 first.

See [this thread (internal)](https://ably-real-time.slack.com/archives/C0114KK7S6R/p1625735057025400).

My observations:

> In terms of project structure, I see:
> 1. files with `_test` suffix in the `/ably` folder
> 2. an `ablytest` folder within the `/ably` folder with files without any "type" suffix
> 3. an `internal/ablyutil` folder within the `/ably` folder with some files having a `_test` suffix

To which @sacOO7 responded:

> It has to do with innate packaging system provided by go
> I think we should absolutely document it somewhere, it took me some time to understand as to why it is, the way it is

The goal is to help a new developer get started on maintaining this project. Also, it's there to help remind those who are coming back to the codebase after a hiatus.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1030) by [Unito](https://www.unito.io)
┆sprint: Backlog

**Comment by Rosalita** [comment]
There have been some file naming conventions adopted since this ticket was written and existing tests have also been split into files that run at different stages of the CI pipeline.

The file name suffix `_test.go` is how Go recognises test files. It's standard practice to give the same name the file that tests as the file that's being tested with this suffix. e.g. `a.go` is tested by `a_test.go` this keeps the test and the code under test side by side in the project. This project had fast tests (unit) and slower tests (integration) that needed separating into layers which ran independently in CI. This was done in https://github.com/ably/ably-go/issues/447

The project contains three packages, `ably`, `ablytest` and `ablyutil` some files suffixed `internal_test.go` will be able to access everything at package level and will have the same package name as the code under test. These files contain the unit tests that we only recently started adding to the project (I think from memory unit. test coverage is around 17%) When these files were first added they were suffixed `internal_test.go` to make it really clear they were internal unit tests.

Other `_test.go` files will be in **packages** which are suffixed  `_test` e.g. `ably_test`, `ablytest_test` ablyutil_test`. These are still unit tests and get compiled as a separate test package and will only have access to the public exposed API (things declared with a capital letter). This is useful technique when building a package and wanting to test the public API surface like a consumer of that package would.

The integration tests in this project, which import package `ablytest` are all now in files suffixed `integration_test.go`.

Then we also have a file called `export_test.go` which is only compiled when running tests, it is used to make private things public while the tests run so they can be tested. This technique should be used sparingly however on this project the `export.go` file has got a little out of hand, as it exports code in 19 different files and the last time I looked we only had about 5 tests that weren't dependent on `export.go`. 

I have documented the majority of this information which is specific to this project in the "Tests" section of the readme file. 

@QuintinWillison it would be great if you could find time to read the "Tests" section of the readme and get back to me with any feedback if you feel anything is unclear or more information needs adding to the readme.

**Comment by QuintinWillison** [comment]
Thanks for checking in with me, @Rosalita. If I ignore the fact that, ideally, the documentation you refer to should be in `CONTRIBUTING.md` rather than the root `README.md` (work pending under #340) then... **Looks good to me.** 😁 

If both you and @mohyour are happy with the current state of this documentation then please feel free to close this issue, as I agree that it's been addressed.
