### ISSUE TITLE
Ablytest

### ISSUE THREAD

**Issue by joshforbes** [ably/ably-go#358]
Hello 👋 

Thanks so much for the hard work in getting 1.2 released - I'm really excited to try it.

To that end, we're trying to update from 1.1.5 to 1.2 but running into some difficulty. Some of the APIs have changed a good deal. But specifically preventing us right now is that `ablytest` has become internal: https://github.com/ably/ably-go/tree/v1.2.0/ably/internal/ablytest

We've been using `ablytest` for integration tests for a long time (since this discussion from last year: https://github.com/ably/ably-go/issues/140). We're setting up a sandbox client and then publishing messages to it to make sure that all of our routing and message handling is working correctly. It has been very useful. 

We use two pieces of the `ablytest` package:

`ablytest.NewRestClient(nil)`
`ablytest.Wait()` (for publishing messages)

Does the Ably team have a recommended replacement for the sandbox client? Or am I missing something?

Thanks!

**Comment by QuintinWillison** [comment]
Hi @joshforbes. Thanks for getting in touch.

As you've discovered, as part of the work to get 1.2 release we were working to conform the APIs exposed by this client library. That work did, indeed, involve encapsulation (i.e. internalisation) of some interfaces that had previously, inadvertently exposed as public.

We have never expected that customers would be using our sandbox test environment within their own testing setups. While it is technically possible, and [somewhat documented](https://docs.ably.com/client-lib-development-guide/test-api/), it's not officially supported for anything but core client library integration test runs (e.g. from workflows in this repository or when running test suites locally as part of client library development workflow).

Could you explain more what you're doing with these integration tests? I would like to understand your use case so I can discuss with the wider team.

Thanks. 😄

**Comment by joshforbes** [comment]
Hey, Quintin 👋  Thanks for looking at this.

> We have never expected that customers would be using our sandbox test environment within their own testing setups. While it is technically possible, and somewhat documented, it's not officially supported for anything but core client library integration test runs (e.g. from workflows in this repository or when running test suites locally as part of client library development workflow).

I'm a bit surprised by that considering that we discussed this in the linked issue and were pointed to the documentation. It seemed like fair game to use in our app code. But I understand that things change.

> Could you explain more what you're doing with these integration tests? I would like to understand your use case so I can discuss with the wider team.

Sure - I think the tests are quite simple but very useful.

We have a good bit of code that interacts with Ably. We have a router that sends different message types to specific message handlers. We have code that reconnects if a token is expired (at least prior to 1.2 that wasn't provided in the go client). We have code that reconnects anytime the connection drops.

So essentially we're testing that code. We set up an Ably sandbox environment, hook a client to it, and start publishing real messages. We're not trying to test that Ably works, we're trying to test that all our code surrounding Ably works. So we have different tests that we can subscribe to a channel, that we handle a message, that we reconnect on disconnect, etc. Since we're using a "real" Ably instance these tests give me high confidence that things are actually working.

Here is an example test with added explanatory comments:

```go
t.Run("subscribe to channel", func(t *testing.T) {
    // setup our own router that contains an ably client
    router := newRouter(t, issueTokenURL, "3")

    // create a test message handler
    msgCh := make(chan *Message)
    router.Route("test-route", func(msg *Message) {
        msgCh <- msg
    })

    // subscribe to the test channel
    if err := router.Subscribe("test"); err != nil {
        t.Fatal(err)
    }

    // grab that channel and send a actual message to it
    channel := router.client.Channels.Get("test")
    if err := ablytest.Wait(channel.Publish("test-route", "data")); err != nil {
        t.Fatal(err)
    }

    select {
    case <-time.After(time.Second * 5):
        t.Fatal("test timed out waiting for test-route handler to be called")
    case msg := <-msgCh:
	if msg.Name != "test-route" {
            t.Fatalf(`got %v, want "test-route"`, msg.Name)
	}
	if msg.Data != "data" {
	    t.Fatalf(`got %v, want "data"`, msg.Data)
	}
    }
})
```

Maybe the test isn't perfect - yes we do have to reach into the client and grab the channel to make it work. But it definitely gives me confidence that my message handlers are going to receive published messages.

Thoughts?

**Comment by sacOO7** [comment]
HI @joshforbes , as a part of 1.2 implementation, we have already implemented auto-reconnect functionality. So, it's natively supported by new version. Maybe, you should migrate to new version first and check if you still need explicit reconnect. I am sure you don't need it as of now : )

**Comment by sacOO7** [comment]
Also, as I can see in the above test code, we are writing integration tests that test whether library works as expected or not along with your own business logic. General rule of thumb, we don't usually test libraries (whether they work properly or not, that's implementation detail and abstracted out so you can build your own code on top of it)
While I do agree, you need to test you own domain specific logic, best solution I would suggest is to mock out library specific handlers, that either publish or receive events, that way you can only focus on code that does things expected to be done assuming library works just fine.

**Comment by joshforbes** [comment]
> HI @joshforbes , as a part of 1.2 implementation, we have already implemented auto-reconnect functionality. So, it's natively supported by new version.

Hey, @sacOO7 do you mind telling me a bit more about the auto-reconnect? We have a ton of code dealing with reconnecting. With version 1.2:

- does it reconnect on any failed or disconnected state?
- does it reattach channels on any failed or disconnected state?
- does it reenter presence?
- how long does it try to reconnect? (forever?)
- how long does it try to reattach channels?
- does it reconnect on token expiry?
- does it now do in-band reauth? (got a bunch of code on our API dealing with this)

Our agent is running on end-user devices and becomes completely unusable if the Ably connection goes away. Hence we do a lot to keep it running and even eventually restart the process if we can't get the connection back. Wondering how much, if any, of this code I can do away with for 1.2. If all of this is part of the library then it certainly would become easier to test on our end.

**Comment by sacOO7** [comment]
- It reconnects when connection goes into `disconnected` state, it keep re-trying for a total time of `connectionStateTTL` (you can configure), with a time gap of `disconnectedRetryTImeout`  (you can configure). Once `connectionStateTTL` is over, it goes into `susended` state and then keeps retrying `indefinitely`, until connection is successful.
- It doesn't try to reconnect when it goes into `failed` state, `failed` state means something unexpected happened and retry might not resolve it.
- So, you might like to keep your code that does reconnect after going into `failed` state
- And yes, it reattach channels (if not in attached state) after getting `reconnected`, also sends pending messages that we might need to send after getting connected. So, thing to note is, this only happens when re-connected internally.
- I am not sure about presence though, whether it re-sends presence messages after reconnection (I cant find the code, maybe presence is more like a message, so we need to send it again explicitly)

**Comment by sacOO7** [comment]
I can see some cases where it will try to re-authorize & reconnect when token is expired or errored on active connection.
I will attach code snippet

**Comment by QuintinWillison** [comment]
Hello @joshforbes - we've discussed this internally, aiming to seek the right balance to get you moving again. 😄 

Ideally, while we've not explicitly documented this anywhere, we would rather it that you didn't use our sandbox environment for testing as this has been provisioned specifically with client library repository testing in mind. As such, for your testing purposes it would be best for you to create separate apps (or even separate accounts) for your testing purposes, which should cover most requirements.

In terms of the `ablytest` package, it has been suggested that we re-export this in a way that would allow you to continue to use it with your own app (as described in my previous paragraph). While I appreciate @sacOO7 doing his best to be helpful in suggestions on this issue, we don't feel it's very user friendly to be telling you to go and copy code into your own tests - as well as bear the cost of maintaining that yourself going forwards. 🤓 

Therefore, I believe the work required to fix this issue is:

1. Re-export the `ablytest` package
2. Modify or enhance the `ablytest` package API to allow you to use your own app for testing, using an Ably API key

I'll discuss with the team getting this work scheduled in.

FYI, @lmars, @AndyNicks, @kavalerov

**Comment by lmars** [comment]
@joshforbes sorry for the delay in getting back to you on this, we've just released [v1.2.1](https://github.com/ably/ably-go/releases/tag/v1.2.1) which includes a revert back to exporting the `ablytest` package, so you should be able to now use that package as you were previously.

**Comment by joshforbes** [comment]
That's excellent news @lmars! I wasn't expecting that. Thank you!

**Comment by joshforbes** [comment]
Just wanted to say - thanks! This will help us take on the 1.2 update much more easily.
