### ISSUE TITLE
Unimplemented Test: TestRealtimeChannel_RTL2_ChannelEventForStateChange ably.ChannelStateAttaching

### ISSUE THREAD

**Issue by tomkirbygreen** [ably/ably-go#394]
┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1283) by [Unito](https://www.unito.io)

**Comment by Rosalita** [comment]
Note: This test appears to be partially implemented. It is not skipped because it is failing it appears to be skipped due to functionality which is missing. It has two sections which are marked as skipped with the following reasons `"SUSPENDED not yet implemented"` and `"UPDATED not yet implemented"`

**Comment by QuintinWillison** [comment]
Work on this should take place under #568.
