### ISSUE TITLE
Unimplemented Test: TestRealtimeChannel_RTL2_ChannelEventForStateChange ably.ChannelEventUpdate

### ISSUE THREAD

**Issue by tomkirbygreen** [ably/ably-go#396]
This skip is a placeholder as the test has yet to be implemented.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1287) by [Unito](https://www.unito.io)

**Comment by Rosalita** [comment]
Note: This test now appears to be partially implemented. It is not skipped because it is failing it appears to be skipped due to functionality which is missing. It has two sections which are marked as skipped with the following reasons `"SUSPENDED not yet implemented"` and `"UPDATED not yet implemented"`

**Comment by QuintinWillison** [comment]
Work on this should take place under #568.
