### ISSUE TITLE
Potential go routine on blocking functions

### ISSUE THREAD

**Issue by davidrenne** [ably/ably-go#623]
In the case of an accidental blocked thread where the calling function has incorrect or bad code:

https://github.com/ably/ably-go/blob/main/ably/realtime_channel.go#L512

An entire set of messages will be blocked forever.  Do you think you can add a go routine for this to prevent this?  I realize every 1 payload will be a go routine, but perhaps you can call the function callback and timeout to kill the go routine somehow if it doesnt return in a certain number of seconds?

It wasnt inherently obvious that these callbacks are synchronous and thus if I have 1 payload which incorrectly hangs a channel without a select timeout, my entire servers pub sub goes down.  Now I have added selects and timeouts if the channel is gone so that these things clear.  So hopefully it solves my problem overall, but I saw this code and wanted to have a discussion about strategies or documentation around a blocking function call that can ruin an entire servers pubsub.

**Comment by sacOO7** [comment]
Hi @davidrenne we have intentionally kept `ably-go` methods as blocking in nature. 
You might like to check => https://github.com/ably/ably-go/blob/main/UPDATING.md
If you don't want to block on the method call, you can externally cancel the context.
Let me know if more information is needed,

**Comment by sacOO7** [comment]
This also means, that if you don't want to wait for the call to return, you have to implement your own mechanism to handle success/failure of the operation asynchronously.
I won't recommend spawning new goroutine for every method call, because creating threads still is a expensive operation and should be managed as a threadpool.
You might like to check https://betterprogramming.pub/building-and-testing-a-worker-pool-in-go-bce4c6da4431

**Comment by sacOO7** [comment]
@davidrenne let us know if you have any update on this, otherwise we will close the issue
